name: voice_translator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  googleapis: ^13.2.0
  record: ^5.1.2
  path_provider: ^2.1.4
  googleapis_auth: ^1.6.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/optical-pillar-431812-k3-03311e42dbb2.json